language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverse-proxy ./deployment
  - docker tag udagram-api-feed andrewserra/udagram-api-feed:latest
  - docker tag udagram-api-user andrewserra/udagram-api-user:latest
  - docker tag udagram-frontend andrewserra/udagram-frontend:latest
  - docker tag reverse-proxy andrewserra/reverse-proxy:latest

after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push andrewserra/udagram-api-feed
 - docker push andrewserra/udagram-api-user
 - docker push andrewserra/udagram-frontend
 - docker push andrewserra/reverse-proxy

