apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: api-feed
        image: andrewserra/udagram-api-feed
        ports:
        - containerPort: 80
      - name: api-user
        image: andrewserra/udagram-api-user
        ports:
        - containerPort: 80

